### ISSUE TITLE
Padding too big with small dock sizes

### ISSUE THREAD

**Issue by adil192** [pop-os/cosmic-dock#152]
With small dock sizes, the padding around the icons gets too big. This is a problem if you want an approximately Windows-sized dock.
Screenshots of an exaggerated case:
<image src="https://user-images.githubusercontent.com/21128619/170044994-7aa434c9-99b8-4cb7-9a22-e8e8f5ad1542.png" width="300"> 10px vs 48px <image src="https://user-images.githubusercontent.com/21128619/170044508-4990f147-dfc3-45f6-9139-3b6935038852.png" width="300">

The solution is to reduce this padding property in smaller docks. Of course hardcoding it isn't ideal, so I tried to change the padding based on the dock size (dash-max-icon-size).

```scss
// _stylesheet.scss

// line 93
#dashtodockContainer.dashtodock .app-well-app  .overview-icon {
    padding: 8px;
}

// ...

// line 160
        .app-well-app  .overview-icon {
            padding: 12px;
        }
```

I've tried doing this myself, but I'm unfamiliar with gnome extensions and this (commented out) code I added in `dash.js` didn't have any effect.

```js
}, class DockDash extends St.Widget {
    // line 594
    _adjustIconSize() {
        // ...
        
        // line 696
        let [targetWidth, targetHeight] = icon.icon.get_size();

        // Scale the icon's texture to the previous size and
        // tween to the new size
        icon.icon.set_size(icon.icon.width * scale,
                           icon.icon.height * scale);
        /*
        // NOT WORKING
        icon.set_style(
            'background: red !important;'
        );
        icon.icon.set_style(
            'background: red !important;'
        );
        */

        icon.icon.ease({
            width: targetWidth,
            height: targetHeight,
            duration: DASH_ANIMATION_TIME,
            mode: Clutter.AnimationMode.EASE_OUT_QUAD,
        });
```

Please can someone direct me on how to add a class / set a style on the `.overview-icon`s?
